services:
  # https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/standalone
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
    ports:
      - "4317:18889"
      - "18888:18888"
  postgres:
    image: postgres:17
    environment:
      - "POSTGRES_PASSWORD=secret"
    ports:
      - "5433:5432"
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5673:5672"
      - "15673:15672"